// Generated by scripts/align-recording.mjs from the human voice recording. Do not edit by hand. Frames are design frames (30fps).
export const FPS = 30;
export const VOICE_LEAD = 0;
export const TOTAL = 2795;
export const VOICE_END = 2695;
/** First frame of every phrase per scene */
export const U: Record<number, number[]> = {"1":[32,44,89,126],"2":[196,220,309,376,407,441],"3":[499,551,595,676],"4":[730,802,844],"5":[925,961,1014],"6":[1099,1171,1212,1307,1391,1445],"7":[1526,1576,1662,1728,1781,1832],"8":[1957,2023,2090,2139,2174,2213],"9":[2247,2305,2361,2393],"10":[2469,2523,2562,2620,2656]};
/** Last frame of every phrase per scene */
export const UE: Record<number, number[]> = {"1":[44,75,126,189],"2":[220,309,369,407,441,494],"3":[551,595,667,717],"4":[802,844,912],"5":[961,1014,1091],"6":[1171,1212,1307,1375,1445,1508],"7":[1576,1644,1714,1771,1816,1921],"8":[2023,2090,2132,2174,2213,2236],"9":[2305,2350,2393,2431],"10":[2523,2562,2620,2656,2695]};
/** Scene cuts, one per scene after the first */
export const CUTS = [182,485,716,911,1085,1512,1943,2233,2455] as const;
/** Start frame of each scene */
export const START: Record<number, number> = {"1":0,"2":182,"3":485,"4":716,"5":911,"6":1085,"7":1512,"8":1943,"9":2233,"10":2455};
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 10 ? TOTAL : START[s + 1]) - START[s];
