// Generated by scripts/align-recording.mjs from the human voice recording. Do not edit by hand. Frames are design frames (30fps).
export const FPS = 30;
export const VOICE_LEAD = 0;
export const TOTAL = 2474;
export const VOICE_END = 2374;
/** First frame of every phrase per scene */
export const U: Record<number, number[]> = {"1":[88,112,147,171,217,251,282,300],"2":[359,387,451],"3":[520,543,598],"4":[668,703,750,804,860,913,956,979],"5":[1041,1071,1138,1199,1235,1274],"6":[1324,1369,1414,1467,1526],"7":[1568,1646,1691,1722,1767,1824,1850,1892],"8":[1927,2004,2052,2101,2166],"9":[2200,2275,2312,2353]};
/** Last frame of every phrase per scene */
export const UE: Record<number, number[]> = {"1":[112,147,161,217,251,282,300,337],"2":[387,451,496],"3":[543,598,652],"4":[703,750,804,852,913,956,979,1013],"5":[1071,1138,1182,1235,1274,1317],"6":[1369,1414,1467,1526,1557],"7":[1646,1691,1722,1760,1824,1850,1892,1915],"8":[2004,2052,2101,2166,2190],"9":[2275,2312,2353,2374]};
/** Scene cuts, one per scene after the first */
export const CUTS = [345,506,654,1027,1310,1554,1913,2186] as const;
/** Start frame of each scene */
export const START: Record<number, number> = {"1":0,"2":345,"3":506,"4":654,"5":1027,"6":1310,"7":1554,"8":1913,"9":2186};
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 9 ? TOTAL : START[s + 1]) - START[s];
