// Generated by scripts/build-voice.mjs from the voice take. Do not edit by hand. Frames are absolute at 30fps.
export const FPS = 30;
export const VOICE_LEAD = 10;
export const TOTAL = 1671;
export const VOICE_END = 1521;
/** First frame of every phrase per voice section */
export const U: Record<number, number[]> = {"1":[11,48],"2":[84,108,153,181,224],"3":[288,339,356,400],"4":[452,543,588],"5":[651,677,695,725,757,769,807,875],"6":[933,971,1043,1087],"7":[1142,1187,1214],"8":[1242,1280,1306,1338,1384],"9":[1419,1463,1502]};
/** Last frame of every phrase per voice section */
export const UE: Record<number, number[]> = {"1":[48,72],"2":[108,140,176,224,276],"3":[331,356,386,440],"4":[527,588,639],"5":[677,695,725,750,757,807,867,921],"6":[961,1034,1077,1130],"7":[1187,1209,1229],"8":[1280,1306,1330,1377,1407],"9":[1451,1494,1521]};
/** Scene cuts (hidden under the diamond wipe), one per scene after the first */
export const CUTS = [76,280,444,643,925,1134,1234,1411] as const;
/** Absolute start frame of each scene */
export const START: Record<number, number> = { 1: 0, 2: 76, 3: 280, 4: 444, 5: 643, 6: 925, 7: 1134, 8: 1234, 9: 1411 };
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 9 ? TOTAL : START[s + 1]) - START[s];
