// Generated by scripts/align-recording.mjs from the human voice recording. Do not edit by hand. Frames are design frames (30fps).
export const FPS = 30;
export const VOICE_LEAD = 0;
export const TOTAL = 2593;
export const VOICE_END = 2493;
/** First frame of every phrase per scene */
export const U: Record<number, number[]> = {"1":[13,71,110,136],"2":[229,305,337,457],"3":[523,562,680],"4":[724,779,886,941,979,1031,1093,1164],"5":[1219,1262,1317,1360,1446],"6":[1517,1552,1626,1704],"7":[1788,1830,1939,1997,2035],"8":[2096,2115,2173,2250],"9":[2306,2358,2392,2448]};
/** Last frame of every phrase per scene */
export const UE: Record<number, number[]> = {"1":[71,110,136,223],"2":[305,337,457,506],"3":[562,680,708],"4":[779,886,941,979,1009,1093,1164,1201],"5":[1262,1317,1360,1446,1493],"6":[1552,1626,1704,1766],"7":[1830,1939,1997,2035,2081],"8":[2115,2173,2250,2280],"9":[2358,2392,2448,2493]};
/** Scene cuts, one per scene after the first */
export const CUTS = [215,509,710,1205,1503,1774,2082,2292] as const;
/** Start frame of each scene */
export const START: Record<number, number> = {"1":0,"2":215,"3":509,"4":710,"5":1205,"6":1503,"7":1774,"8":2082,"9":2292};
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 9 ? TOTAL : START[s + 1]) - START[s];
