// Generated by scripts/build-voice.mjs from the voice take. Do not edit by hand. Frames are absolute at 30fps.
export const FPS = 30;
export const VOICE_LEAD = 10;
export const TOTAL = 929;
export const VOICE_END = 779;
/** First frame of every phrase per voice section */
export const U: Record<number, number[]> = {"1":[11,59],"2":[97,142,194,214,245],"3":[277,327,347,371,405],"4":[441,477],"5":[545,598],"6":[655,700,738,759]};
/** Last frame of every phrase per voice section */
export const UE: Record<number, number[]> = {"1":[59,85],"2":[142,190,214,245,265],"3":[321,347,371,398,429],"4":[477,533],"5":[598,643],"6":[700,726,753,779]};
/** Scene cuts (hidden under the diamond wipe), one per scene after the first */
export const CUTS = [89,269,433,537,647] as const;
/** Absolute start frame of each scene */
export const START: Record<number, number> = { 1: 0, 2: 89, 3: 269, 4: 433, 5: 537, 6: 647 };
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 6 ? TOTAL : START[s + 1]) - START[s];
