// Generated by scripts/build-voice.mjs from the voice take. Do not edit by hand. Frames are absolute at 30fps.
export const FPS = 30;
export const VOICE_LEAD = 10;
export const TOTAL = 801;
export const VOICE_END = 701;
/** First frame of every phrase per voice section */
export const U: Record<number, number[]> = {"1":[11,55],"2":[87,128,177,195,223],"3":[249,295,314,336,367],"4":[397,430],"5":[489,538],"6":[587,628,664,683]};
/** Last frame of every phrase per voice section */
export const UE: Record<number, number[]> = {"1":[55,79],"2":[128,172,195,223,241],"3":[290,314,336,361,390],"4":[430,481],"5":[538,580],"6":[628,653,678,701]};
/** Scene cuts (hidden under the diamond wipe), one per scene after the first */
export const CUTS = [79,241,389,481,579] as const;
/** Absolute start frame of each scene */
export const START: Record<number, number> = { 1: 0, 2: 79, 3: 241, 4: 389, 5: 481, 6: 579 };
/** Local frame of phrase k in scene s (offset by `extra` frames) */
export const at = (s: number, k: number, extra = 0): number => U[s][k] - START[s] + extra;
export const endAt = (s: number, k: number, extra = 0): number => UE[s][k] - START[s] + extra;
/** Duration in frames of scene s */
export const dur = (s: number): number => (s === 6 ? TOTAL : START[s + 1]) - START[s];
